[tool.poetry]
name = "wordlebot"
version = "0.1.0"
description = ""
authors = ["Parker Wahle <regulad@regulad.xyz>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
